module.exports = [
    {
        'id': 1,
        'totalPrice': 614.95,
        'date': '2023-10-05',
        'status': 'Processing',
        'taxId': 1,
        'deliveryFee': 10.00,
        'paymentId': 1,
        'cartId': 1,
        'userId': 2,
        'addressId': 1,
        'discountId': 1
    },
    {
        'id': 2,
        'totalPrice': 220.45,
        'date': '2023-10-06',
        'status': 'Shipped',
        'taxId': 2,
        'deliveryFee': 8.00,
        'paymentId': 2,
        'cartId': 2,
        'userId': 3,
        'addressId': 2,
        'discountId': 2
    },
    {
        'id': 3,
        'totalPrice': 635.23,
        'date': '2023-10-07',
        'status': 'Delivered',
        'taxId': 3,
        'deliveryFee': 15.00,
        'paymentId': 3,
        'cartId': 1,
        'userId': 2,
        'addressId': 3,
        'discountId': 3
    },
    {
        'id': 4,
        'totalPrice': 80.75,
        'date': '2023-10-08',
        'status': 'Processing',
        'taxId': 4,
        'deliveryFee': 5.00,
        'paymentId': 4,
        'cartId': 1,
        'userId': 2,
        'addressId': 4,
        'discountId': 1
    },
    {
        'id': 5,
        'totalPrice': 300.00,
        'date': '2023-10-09',
        'status': 'Shipped',
        'taxId': 5,
        'deliveryFee': 20.00,
        'paymentId': 5,
        'cartId': 2,
        'userId': 3,
        'addressId': 5,
        'discountId': 2
    },
];
