module.exports = [
    {
      'id': 1,
      'countryCode': 'US',
      'countryName': 'United States',
      'taxRate': 7.5,
    },
    {
      'id': 2,
      'countryCode': 'CA',
      'countryName': 'Canada',
      'taxRate': 5.0,
    },
    {
      'id': 3,
      'countryCode': 'UK',
      'countryName': 'United Kingdom',
      'taxRate': 6.0,
    },
    {
      'id': 4,
      'countryCode': 'FR',
      'countryName': 'France',
      'taxRate': 5.5,
    },
    {
      'id': 5,
      'countryCode': 'DE',
      'countryName': 'Germany',
      'taxRate': 7.0,
    },
    {
      'id': 6,
      'countryCode': 'AU',
      'countryName': 'Australia',
      'taxRate': 10.0,
    },
    {
      'id': 7,
      'countryCode': 'JP',
      'countryName': 'Japan',
      'taxRate': 8.0,
    },
    {
      'id': 8,
      'countryCode': 'IT',
      'countryName': 'Italy',
      'taxRate': 6.0,
    },
    {
      'id': 9,
      'countryCode': 'BR',
      'countryName': 'Brazil',
      'taxRate': 12.5,
    },
    {
      'id': 10,
      'countryCode': 'IN',
      'countryName': 'India',
      'taxRate': 18.0,
    },
    {
      'id': 11,
      'countryCode': 'CN',
      'countryName': 'China',
      'taxRate': 13.5,
    },
    {
      'id': 12,
      'countryCode': 'MX',
      'countryName': 'Mexico',
      'taxRate': 16.0,
    },
    {
      'id': 13,
      'countryCode': 'RU',
      'countryName': 'Russia',
      'taxRate': 15.0,
    },
    {
      'id': 14,
      'countryCode': 'ES',
      'countryName': 'Spain',
      'taxRate': 7.5,
    },
    {
      'id': 15,
      'countryCode': 'KR',
      'countryName': 'South Korea',
      'taxRate': 9.0,
    },
    {
      'id': 16,
      'countryCode': 'SA',
      'countryName': 'Saudi Arabia',
      'taxRate': 5.5,
    },
    {
      'id': 17,
      'countryCode': 'ZA',
      'countryName': 'South Africa',
      'taxRate': 10.5,
    },
    {
      'id': 18,
      'countryCode': 'NL',
      'countryName': 'Netherlands',
      'taxRate': 6.0,
    },
    {
      'id': 19,
      'countryCode': 'SE',
      'countryName': 'Sweden',
      'taxRate': 7.0,
    },
    {
      'id': 20,
      'countryCode': 'SG',
      'countryName': 'Singapore',
      'taxRate': 7.5,
    },
    {
      'id': 21,
      'countryCode': 'TH',
      'countryName': 'Thailand',
      'taxRate': 7.0,
    },
    {
      'id': 22,
      'countryCode': 'AR',
      'countryName': 'Argentina',
      'taxRate': 8.5,
    },
    {
      'id': 23,
      'countryCode': 'EG',
      'countryName': 'Egypt',
      'taxRate': 9.0,
    },
    {
      'id': 24,
      'countryCode': 'TR',
      'countryName': 'Turkey',
      'taxRate': 8.0,
    },
    {
      'id': 25,
      'countryCode': 'CH',
      'countryName': 'Switzerland',
      'taxRate': 7.0,
    },
    {
      'id': 26,
      'countryCode': 'BE',
      'countryName': 'Belgium',
      'taxRate': 6.0,
    },
    {
      'id': 27,
      'countryCode': 'AT',
      'countryName': 'Austria',
      'taxRate': 5.0,
    },
];
  
